/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioDothtmlRouteImport } from './routes/studio[.]html'
import { Route as PWiseOwlRouteImport } from './routes/p/wise-owl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDothtmlRoute = StudioDothtmlRouteImport.update({
  id: '/studio.html',
  path: '/studio.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PWiseOwlRoute = PWiseOwlRouteImport.update({
  id: '/p/wise-owl',
  path: '/p/wise-owl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/logo': typeof LogoRoute
  '/onboard': typeof OnboardRoute
  '/studio': typeof StudioRoute
  '/studio.html': typeof StudioDothtmlRoute
  '/p/wise-owl': typeof PWiseOwlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/logo': typeof LogoRoute
  '/onboard': typeof OnboardRoute
  '/studio': typeof StudioRoute
  '/studio.html': typeof StudioDothtmlRoute
  '/p/wise-owl': typeof PWiseOwlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/logo': typeof LogoRoute
  '/onboard': typeof OnboardRoute
  '/studio': typeof StudioRoute
  '/studio.html': typeof StudioDothtmlRoute
  '/p/wise-owl': typeof PWiseOwlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoice'
    | '/login'
    | '/logo'
    | '/onboard'
    | '/studio'
    | '/studio.html'
    | '/p/wise-owl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoice'
    | '/login'
    | '/logo'
    | '/onboard'
    | '/studio'
    | '/studio.html'
    | '/p/wise-owl'
  id:
    | '__root__'
    | '/'
    | '/invoice'
    | '/login'
    | '/logo'
    | '/onboard'
    | '/studio'
    | '/studio.html'
    | '/p/wise-owl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoiceRoute: typeof InvoiceRoute
  LoginRoute: typeof LoginRoute
  LogoRoute: typeof LogoRoute
  OnboardRoute: typeof OnboardRoute
  StudioRoute: typeof StudioRoute
  StudioDothtmlRoute: typeof StudioDothtmlRoute
  PWiseOwlRoute: typeof PWiseOwlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio.html': {
      id: '/studio.html'
      path: '/studio.html'
      fullPath: '/studio.html'
      preLoaderRoute: typeof StudioDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/wise-owl': {
      id: '/p/wise-owl'
      path: '/p/wise-owl'
      fullPath: '/p/wise-owl'
      preLoaderRoute: typeof PWiseOwlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoiceRoute: InvoiceRoute,
  LoginRoute: LoginRoute,
  LogoRoute: LogoRoute,
  OnboardRoute: OnboardRoute,
  StudioRoute: StudioRoute,
  StudioDothtmlRoute: StudioDothtmlRoute,
  PWiseOwlRoute: PWiseOwlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
