/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioDothtmlRouteImport } from './routes/studio[.]html'
import { Route as PWiseOwlRouteImport } from './routes/p/wise-owl'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StudioClientsIdRouteImport } from './routes/studio/clients/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDothtmlRoute = StudioDothtmlRouteImport.update({
  id: '/studio.html',
  path: '/studio.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PWiseOwlRoute = PWiseOwlRouteImport.update({
  id: '/p/wise-owl',
  path: '/p/wise-owl',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioClientsIdRoute = StudioClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/onboard': typeof OnboardRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio.html': typeof StudioDothtmlRoute
  '/p/wise-owl': typeof PWiseOwlRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/onboard': typeof OnboardRoute
  '/studio.html': typeof StudioDothtmlRoute
  '/p/wise-owl': typeof PWiseOwlRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logo': typeof LogoRoute
  '/onboard': typeof OnboardRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio.html': typeof StudioDothtmlRoute
  '/p/wise-owl': typeof PWiseOwlRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logo'
    | '/onboard'
    | '/studio'
    | '/studio.html'
    | '/p/wise-owl'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logo'
    | '/onboard'
    | '/studio.html'
    | '/p/wise-owl'
    | '/studio'
    | '/api/auth/$'
    | '/studio/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/logo'
    | '/onboard'
    | '/studio'
    | '/studio.html'
    | '/p/wise-owl'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogoRoute: typeof LogoRoute
  OnboardRoute: typeof OnboardRoute
  StudioRoute: typeof StudioRouteWithChildren
  StudioDothtmlRoute: typeof StudioDothtmlRoute
  PWiseOwlRoute: typeof PWiseOwlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio.html': {
      id: '/studio.html'
      path: '/studio.html'
      fullPath: '/studio.html'
      preLoaderRoute: typeof StudioDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/wise-owl': {
      id: '/p/wise-owl'
      path: '/p/wise-owl'
      fullPath: '/p/wise-owl'
      preLoaderRoute: typeof PWiseOwlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/clients/$id': {
      id: '/studio/clients/$id'
      path: '/clients/$id'
      fullPath: '/studio/clients/$id'
      preLoaderRoute: typeof StudioClientsIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
  StudioClientsIdRoute: typeof StudioClientsIdRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
  StudioClientsIdRoute: StudioClientsIdRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogoRoute: LogoRoute,
  OnboardRoute: OnboardRoute,
  StudioRoute: StudioRouteWithChildren,
  StudioDothtmlRoute: StudioDothtmlRoute,
  PWiseOwlRoute: PWiseOwlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
